/*
 * BT Shipping
 *
 * TODO: Add Description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using ApiMovies.Models;
using ApiMovies.DataAccess;
using Microsoft.AspNetCore.Http;
using ApiMovies.DataAccess.Interfaces;

namespace ApiMovies.Controllers
{

    [ApiController]
    public class MoviesApiController : ControllerBase
    {
        private readonly IMovieRepository _movieRepository;

        public MoviesApiController(IMovieRepository injectedRepo)
        {
            this._movieRepository = injectedRepo;
        }

        [HttpGet]
        [Route("/movies")]
        public virtual IActionResult GetMovies()
        {
            List<Movie> movies = _movieRepository.GetAll();

            return new JsonResult(movies);
        }

        [HttpPost]
        [Route("/movies")]
        public virtual IActionResult CreateMoview([FromBody] Movie movieInput)
        {
            Movie createdMovie = _movieRepository.Insert(movieInput);
            if(createdMovie != null)
            {
                return new ObjectResult(createdMovie) { StatusCode = StatusCodes.Status201Created };
            }
            else
            {
                //return new ObjectResult(createdMovie == null);
                return BadRequest();
            }
        }

    }
}